/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.kernel.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LayoutSetVersion service. Represents a row in the &quot;LayoutSetVersion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.portal.model.impl.LayoutSetVersionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.portal.model.impl.LayoutSetVersionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LayoutSetVersion
 * @see com.liferay.portal.model.impl.LayoutSetVersionImpl
 * @see com.liferay.portal.model.impl.LayoutSetVersionModelImpl
 * @generated
 */
@ProviderType
public interface LayoutSetVersionModel extends BaseModel<LayoutSetVersion>,
	MVCCModel, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a layout set version model instance should use the {@link LayoutSetVersion} interface instead.
	 */

	/**
	 * Returns the primary key of this layout set version.
	 *
	 * @return the primary key of this layout set version
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this layout set version.
	 *
	 * @param primaryKey the primary key of this layout set version
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this layout set version.
	 *
	 * @return the mvcc version of this layout set version
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this layout set version.
	 *
	 * @param mvccVersion the mvcc version of this layout set version
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the layout set version ID of this layout set version.
	 *
	 * @return the layout set version ID of this layout set version
	 */
	public long getLayoutSetVersionId();

	/**
	 * Sets the layout set version ID of this layout set version.
	 *
	 * @param layoutSetVersionId the layout set version ID of this layout set version
	 */
	public void setLayoutSetVersionId(long layoutSetVersionId);

	/**
	 * Returns the company ID of this layout set version.
	 *
	 * @return the company ID of this layout set version
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this layout set version.
	 *
	 * @param companyId the company ID of this layout set version
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this layout set version.
	 *
	 * @return the create date of this layout set version
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this layout set version.
	 *
	 * @param createDate the create date of this layout set version
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this layout set version.
	 *
	 * @return the modified date of this layout set version
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this layout set version.
	 *
	 * @param modifiedDate the modified date of this layout set version
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the layout set resource ID of this layout set version.
	 *
	 * @return the layout set resource ID of this layout set version
	 */
	public long getLayoutSetResourceId();

	/**
	 * Sets the layout set resource ID of this layout set version.
	 *
	 * @param layoutSetResourceId the layout set resource ID of this layout set version
	 */
	public void setLayoutSetResourceId(long layoutSetResourceId);

	/**
	 * Returns the logo ID of this layout set version.
	 *
	 * @return the logo ID of this layout set version
	 */
	public long getLogoId();

	/**
	 * Sets the logo ID of this layout set version.
	 *
	 * @param logoId the logo ID of this layout set version
	 */
	public void setLogoId(long logoId);

	/**
	 * Returns the theme ID of this layout set version.
	 *
	 * @return the theme ID of this layout set version
	 */
	@AutoEscape
	public String getThemeId();

	/**
	 * Sets the theme ID of this layout set version.
	 *
	 * @param themeId the theme ID of this layout set version
	 */
	public void setThemeId(String themeId);

	/**
	 * Returns the color scheme ID of this layout set version.
	 *
	 * @return the color scheme ID of this layout set version
	 */
	@AutoEscape
	public String getColorSchemeId();

	/**
	 * Sets the color scheme ID of this layout set version.
	 *
	 * @param colorSchemeId the color scheme ID of this layout set version
	 */
	public void setColorSchemeId(String colorSchemeId);

	/**
	 * Returns the css of this layout set version.
	 *
	 * @return the css of this layout set version
	 */
	@AutoEscape
	public String getCss();

	/**
	 * Sets the css of this layout set version.
	 *
	 * @param css the css of this layout set version
	 */
	public void setCss(String css);

	/**
	 * Returns the settings of this layout set version.
	 *
	 * @return the settings of this layout set version
	 */
	@AutoEscape
	public String getSettings();

	/**
	 * Sets the settings of this layout set version.
	 *
	 * @param settings the settings of this layout set version
	 */
	public void setSettings(String settings);

	/**
	 * Returns the layout set prototype uuid of this layout set version.
	 *
	 * @return the layout set prototype uuid of this layout set version
	 */
	@AutoEscape
	public String getLayoutSetPrototypeUuid();

	/**
	 * Sets the layout set prototype uuid of this layout set version.
	 *
	 * @param layoutSetPrototypeUuid the layout set prototype uuid of this layout set version
	 */
	public void setLayoutSetPrototypeUuid(String layoutSetPrototypeUuid);

	/**
	 * Returns the layout set prototype link enabled of this layout set version.
	 *
	 * @return the layout set prototype link enabled of this layout set version
	 */
	public boolean getLayoutSetPrototypeLinkEnabled();

	/**
	 * Returns <code>true</code> if this layout set version is layout set prototype link enabled.
	 *
	 * @return <code>true</code> if this layout set version is layout set prototype link enabled; <code>false</code> otherwise
	 */
	public boolean isLayoutSetPrototypeLinkEnabled();

	/**
	 * Sets whether this layout set version is layout set prototype link enabled.
	 *
	 * @param layoutSetPrototypeLinkEnabled the layout set prototype link enabled of this layout set version
	 */
	public void setLayoutSetPrototypeLinkEnabled(
		boolean layoutSetPrototypeLinkEnabled);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LayoutSetVersion layoutSetVersion);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LayoutSetVersion> toCacheModel();

	@Override
	public LayoutSetVersion toEscapedModel();

	@Override
	public LayoutSetVersion toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}