/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.asset.kernel.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.LocalizedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.version.VersionModel;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

/**
 * The base model interface for the AssetCategoryVersion service. Represents a row in the &quot;AssetCategoryVersion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.portlet.asset.model.impl.AssetCategoryVersionModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.portlet.asset.model.impl.AssetCategoryVersionImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AssetCategoryVersion
 * @generated
 */
@ProviderType
public interface AssetCategoryVersionModel extends BaseModel<AssetCategoryVersion>,
	GroupedModel, LocalizedModel, ShardedModel, VersionModel<AssetCategory> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a asset category version model instance should use the {@link AssetCategoryVersion} interface instead.
	 */

	/**
	 * Returns the primary key of this asset category version.
	 *
	 * @return the primary key of this asset category version
	 */
	@Override
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this asset category version.
	 *
	 * @param primaryKey the primary key of this asset category version
	 */
	@Override
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the asset category version ID of this asset category version.
	 *
	 * @return the asset category version ID of this asset category version
	 */
	public long getAssetCategoryVersionId();

	/**
	 * Sets the asset category version ID of this asset category version.
	 *
	 * @param assetCategoryVersionId the asset category version ID of this asset category version
	 */
	public void setAssetCategoryVersionId(long assetCategoryVersionId);

	/**
	 * Returns the version of this asset category version.
	 *
	 * @return the version of this asset category version
	 */
	@Override
	public int getVersion();

	/**
	 * Sets the version of this asset category version.
	 *
	 * @param version the version of this asset category version
	 */
	@Override
	public void setVersion(int version);

	/**
	 * Returns the uuid of this asset category version.
	 *
	 * @return the uuid of this asset category version
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this asset category version.
	 *
	 * @param uuid the uuid of this asset category version
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the external reference code of this asset category version.
	 *
	 * @return the external reference code of this asset category version
	 */
	@AutoEscape
	public String getExternalReferenceCode();

	/**
	 * Sets the external reference code of this asset category version.
	 *
	 * @param externalReferenceCode the external reference code of this asset category version
	 */
	public void setExternalReferenceCode(String externalReferenceCode);

	/**
	 * Returns the category ID of this asset category version.
	 *
	 * @return the category ID of this asset category version
	 */
	public long getCategoryId();

	/**
	 * Sets the category ID of this asset category version.
	 *
	 * @param categoryId the category ID of this asset category version
	 */
	public void setCategoryId(long categoryId);

	/**
	 * Returns the group ID of this asset category version.
	 *
	 * @return the group ID of this asset category version
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this asset category version.
	 *
	 * @param groupId the group ID of this asset category version
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this asset category version.
	 *
	 * @return the company ID of this asset category version
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this asset category version.
	 *
	 * @param companyId the company ID of this asset category version
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this asset category version.
	 *
	 * @return the user ID of this asset category version
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this asset category version.
	 *
	 * @param userId the user ID of this asset category version
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this asset category version.
	 *
	 * @return the user uuid of this asset category version
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this asset category version.
	 *
	 * @param userUuid the user uuid of this asset category version
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this asset category version.
	 *
	 * @return the user name of this asset category version
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this asset category version.
	 *
	 * @param userName the user name of this asset category version
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this asset category version.
	 *
	 * @return the create date of this asset category version
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this asset category version.
	 *
	 * @param createDate the create date of this asset category version
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this asset category version.
	 *
	 * @return the modified date of this asset category version
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this asset category version.
	 *
	 * @param modifiedDate the modified date of this asset category version
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the parent category ID of this asset category version.
	 *
	 * @return the parent category ID of this asset category version
	 */
	public long getParentCategoryId();

	/**
	 * Sets the parent category ID of this asset category version.
	 *
	 * @param parentCategoryId the parent category ID of this asset category version
	 */
	public void setParentCategoryId(long parentCategoryId);

	/**
	 * Returns the left category ID of this asset category version.
	 *
	 * @return the left category ID of this asset category version
	 */
	public long getLeftCategoryId();

	/**
	 * Sets the left category ID of this asset category version.
	 *
	 * @param leftCategoryId the left category ID of this asset category version
	 */
	public void setLeftCategoryId(long leftCategoryId);

	/**
	 * Returns the right category ID of this asset category version.
	 *
	 * @return the right category ID of this asset category version
	 */
	public long getRightCategoryId();

	/**
	 * Sets the right category ID of this asset category version.
	 *
	 * @param rightCategoryId the right category ID of this asset category version
	 */
	public void setRightCategoryId(long rightCategoryId);

	/**
	 * Returns the name of this asset category version.
	 *
	 * @return the name of this asset category version
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this asset category version.
	 *
	 * @param name the name of this asset category version
	 */
	public void setName(String name);

	/**
	 * Returns the title of this asset category version.
	 *
	 * @return the title of this asset category version
	 */
	public String getTitle();

	/**
	 * Returns the localized title of this asset category version in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized title of this asset category version
	 */
	@AutoEscape
	public String getTitle(Locale locale);

	/**
	 * Returns the localized title of this asset category version in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized title of this asset category version. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getTitle(Locale locale, boolean useDefault);

	/**
	 * Returns the localized title of this asset category version in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized title of this asset category version
	 */
	@AutoEscape
	public String getTitle(String languageId);

	/**
	 * Returns the localized title of this asset category version in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized title of this asset category version
	 */
	@AutoEscape
	public String getTitle(String languageId, boolean useDefault);

	@AutoEscape
	public String getTitleCurrentLanguageId();

	@AutoEscape
	public String getTitleCurrentValue();

	/**
	 * Returns a map of the locales and localized titles of this asset category version.
	 *
	 * @return the locales and localized titles of this asset category version
	 */
	public Map<Locale, String> getTitleMap();

	/**
	 * Sets the title of this asset category version.
	 *
	 * @param title the title of this asset category version
	 */
	public void setTitle(String title);

	/**
	 * Sets the localized title of this asset category version in the language.
	 *
	 * @param title the localized title of this asset category version
	 * @param locale the locale of the language
	 */
	public void setTitle(String title, Locale locale);

	/**
	 * Sets the localized title of this asset category version in the language, and sets the default locale.
	 *
	 * @param title the localized title of this asset category version
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setTitle(String title, Locale locale, Locale defaultLocale);

	public void setTitleCurrentLanguageId(String languageId);

	/**
	 * Sets the localized titles of this asset category version from the map of locales and localized titles.
	 *
	 * @param titleMap the locales and localized titles of this asset category version
	 */
	public void setTitleMap(Map<Locale, String> titleMap);

	/**
	 * Sets the localized titles of this asset category version from the map of locales and localized titles, and sets the default locale.
	 *
	 * @param titleMap the locales and localized titles of this asset category version
	 * @param defaultLocale the default locale
	 */
	public void setTitleMap(Map<Locale, String> titleMap, Locale defaultLocale);

	/**
	 * Returns the description of this asset category version.
	 *
	 * @return the description of this asset category version
	 */
	public String getDescription();

	/**
	 * Returns the localized description of this asset category version in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized description of this asset category version
	 */
	@AutoEscape
	public String getDescription(Locale locale);

	/**
	 * Returns the localized description of this asset category version in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this asset category version. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getDescription(Locale locale, boolean useDefault);

	/**
	 * Returns the localized description of this asset category version in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized description of this asset category version
	 */
	@AutoEscape
	public String getDescription(String languageId);

	/**
	 * Returns the localized description of this asset category version in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this asset category version
	 */
	@AutoEscape
	public String getDescription(String languageId, boolean useDefault);

	@AutoEscape
	public String getDescriptionCurrentLanguageId();

	@AutoEscape
	public String getDescriptionCurrentValue();

	/**
	 * Returns a map of the locales and localized descriptions of this asset category version.
	 *
	 * @return the locales and localized descriptions of this asset category version
	 */
	public Map<Locale, String> getDescriptionMap();

	/**
	 * Sets the description of this asset category version.
	 *
	 * @param description the description of this asset category version
	 */
	public void setDescription(String description);

	/**
	 * Sets the localized description of this asset category version in the language.
	 *
	 * @param description the localized description of this asset category version
	 * @param locale the locale of the language
	 */
	public void setDescription(String description, Locale locale);

	/**
	 * Sets the localized description of this asset category version in the language, and sets the default locale.
	 *
	 * @param description the localized description of this asset category version
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setDescription(String description, Locale locale,
		Locale defaultLocale);

	public void setDescriptionCurrentLanguageId(String languageId);

	/**
	 * Sets the localized descriptions of this asset category version from the map of locales and localized descriptions.
	 *
	 * @param descriptionMap the locales and localized descriptions of this asset category version
	 */
	public void setDescriptionMap(Map<Locale, String> descriptionMap);

	/**
	 * Sets the localized descriptions of this asset category version from the map of locales and localized descriptions, and sets the default locale.
	 *
	 * @param descriptionMap the locales and localized descriptions of this asset category version
	 * @param defaultLocale the default locale
	 */
	public void setDescriptionMap(Map<Locale, String> descriptionMap,
		Locale defaultLocale);

	/**
	 * Returns the vocabulary ID of this asset category version.
	 *
	 * @return the vocabulary ID of this asset category version
	 */
	public long getVocabularyId();

	/**
	 * Sets the vocabulary ID of this asset category version.
	 *
	 * @param vocabularyId the vocabulary ID of this asset category version
	 */
	public void setVocabularyId(long vocabularyId);

	/**
	 * Returns the last publish date of this asset category version.
	 *
	 * @return the last publish date of this asset category version
	 */
	public Date getLastPublishDate();

	/**
	 * Sets the last publish date of this asset category version.
	 *
	 * @param lastPublishDate the last publish date of this asset category version
	 */
	public void setLastPublishDate(Date lastPublishDate);

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;
}